#  Операции со списками/векторами в Python и в NumPy

Создание функции, которая создает массив чисел указанной длины, возводит его в квадрат и куб, складывает и возвращает результат.

In [11]:
def pythonsum(n):
    a = list(range(n)) # еще раз: a = range(n) больше не работает как генератор
    b = list(range(n))
    c = []
    
    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

In [5]:
def numpysum(n):
    import numpy as np
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [12]:
%timeit pythonsum(100)

115 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
%timeit numpysum(100)

11.4 µs ± 344 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Массивы в NumPy

Массивы в NumPy сотоят из
- данных
- метаданных, описывающих данные

Можно создавать многомерные и одномерные массивы (ndarray).
data type: ndarray.dtype
shape: ndarray.shape

In [16]:
import numpy as np

In [18]:
a = np.arange(5) # создаем вектор
a.dtype #data type

dtype('int64')

In [19]:
a.shape #shape

(5,)

array создает массив NumPy

In [22]:
m = np.array([np.arange(2), np.arange(2)])
print(m.dtype, '\n', m.shape)

int64 
 (2, 2)


Как работает индексирование

In [26]:
c = np.array([[1, 2], [3, 4]])
print(c)
print(c.dtype, '\n', c.shape)
print('index [0] is for {}'.format(c[0]))
print('index [1] is for {}'.format(c[1]))
print('index [0, 0] is for {}'.format(c[0, 0]))
print('index [0, 1] is for {}'.format(c[0, 1]))
print('index [1, 0] is for {}'.format(c[1, 0]))
print('index [1, 1] is for {}'.format(c[1, 1]))

[[1 2]
 [3 4]]
int64 
 (2, 2)
index [0] is for [1 2]
index [1] is for [3 4]
index [0, 0] is for 1
index [0, 1] is for 2
index [1, 0] is for 3
index [1, 1] is for 4


Типы данных в NumPy:
- bool
- inti (platform integer)
- int8
- int16
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float16
- float32
- float64 or floatcomplex64
- complex (complex128)
можно передавать функции arange в виде аргумента dtype

In [35]:
d = np.arange(5, dtype=float)
print(d.dtype)

float64


Есть короткие варианты:
- i (integer)
- u (unsigned integer)
- f (single precision float)
- d (double precision float)
- b (bool)
- D (complex)
- S (string)
- U (unicode)
- V (Void)

In [34]:
f = np.arange(5, dtype='f')
print(f.dtype)

float32


По умолчанию NumPy считает, что все данные - float
Чтобы задать его для разных данных можно воспользоваться следующим приемом

In [40]:
t = np.dtype([('name', str, 40), ('numitems', int), ('price', float)])

In [48]:
items = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)
print(items)

[('Meaning of life DVD', 42, 3.14) ('Butter', 13, 2.72)]


# Срезы

In [49]:
b = np.arange(24).reshape(2, 3, 4)
b.shape

(2, 3, 4)

In [51]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
b[0, 0, 0] # элемент

0

In [53]:
b[:,0, 0] # нулевые элементы в двух списках внутри списка

array([ 0, 12])

In [54]:
b[0] # список с индексом 0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b[0, ...] # еще один способ

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
b[0, :, :] # и еще один ":" = все

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b[0,1, ::2] # элементы из всех элементов внутри списка 1 внутри списка 0 с шагом 2

array([4, 6])

In [58]:
b[..., 1] # все элементы во втором столбце

array([[ 1,  5,  9],
       [13, 17, 21]])

In [59]:
b[:,1] #вторая строка обоих списков

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [60]:
b[0, :, 1] #второй столбец второго списка

array([1, 5, 9])

In [61]:
b[0,:, -1] # последний столбец второго списка

array([ 3,  7, 11])

In [62]:
b[0,::-1, -1] # последний столбец в обратном порядке

array([11,  7,  3])

In [63]:
b[0, ::2, -1] # каждый второй элемент последовательности

array([ 3, 11])

In [64]:
b[::-1] # список в обратном порядке

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])