In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(2, 3, 4)

Преобразование в одномерный массив:
- метод .ravel() - возвращает измененный изначальный массив (изменения фиксируются и отображаются в исходном)
- метод flatten() - возвращает копию, может быть вызван только для массива ndarray

In [9]:
a.ravel() * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [5]:
print(a.flatten())
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
a.reshape((-1,)) # еще один способ

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
a.shape = (6, 4) # создает новый массив из шести строк и четырех столбцов

In [13]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
a.transpose() # транспонирует матрицу (по диагонали)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [15]:
a.resize((2,12)) # Как и reshape, но меняет массив, а не возвращает копию (важно: принимает кортеж в качестве аргумента)

In [16]:
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


## Объединение массивов

In [18]:
a = np.arange(9).reshape(3, 3)

In [19]:
b = a * 2

In [22]:
np.hstack((a, b)) #объединение по горизонтали (принимает кортеж)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [23]:
np.concatenate((a, b), axis=1) # делает то же самое

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [24]:
np.vstack((a, b)) # объединение по вертикали

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [25]:
np.concatenate((a, b), axis=0) # делает то же самое

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [26]:
np.dstack((a, b)) # объединяет элементы массивов попарно, создает еще один уровень вложенности

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [27]:
oned = np.arange(2)
twiceoned = oned * 2
np.column_stack((oned, twiceoned))

array([[0, 0],
       [1, 2]])

In [28]:
np.column_stack((a, b)) # = .hstack()

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [30]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [31]:
np.row_stack((oned, twiceoned)) # = .vstack()

array([[0, 1],
       [0, 2]])

In [32]:
np.row_stack((a, b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Splitting

In [35]:
np.hsplit(a, 3) # разбивает по столбцам, принимает название массива и количество необходимых столбцов

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [36]:
np.split(a, 3, axis=1) # то же самое, но требуеющего доп аргумента для метода split()

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [37]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [38]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [40]:
c = np.arange(27).reshape(3, 3, 3)

In [41]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

## Атрибуты массивов

In [43]:
b.ndim #размерность массива

2

In [44]:
b.size #количество элементов

9

In [45]:
b.itemsize #количество занимаемых элементов байтов

8

In [46]:
b.nbytes #количество занимаемых массивом данных

72

In [47]:
b.size * b.itemsize

72

In [49]:
b = np.arange(24).reshape(2, 12)

In [51]:
b.resize(6, 4)

In [52]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [54]:
b.ndim

2

In [56]:
b = np.array([1.j + 1, 2.j + 3])

In [57]:
b.real # только реальную часть комплексных чисел

array([1., 3.])

In [58]:
b.imag # только мнимая часть

array([1., 2.])

In [59]:
b.flat = 7

In [60]:
b

array([7.+0.j, 7.+0.j])