# Сохранение и открытие файлов

In [1]:
import numpy as np

In [2]:
a = np.eye(4) # создает диагональную матрицу из единиц; аргумент - длина диагонали

In [3]:
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
np.savetxt('eye.txt', a) # сохраняет массив в файле

In [21]:
b = np.random.random(100).reshape(50, 2) # два столбца, 50 строк, 100 значений по порядку

In [22]:
np.savetxt('array.csv', b, delimiter = ',') 

In [23]:
i, j = np.loadtxt('array.csv', delimiter = ',', usecols=(0,1), unpack=True) # выгружаем содержимое csv

## Mean and average

**Volume weighted average (VWA)** - просто среднее - чем чаще встречается, тем больше вес

In [27]:
print('The average of the first sample is {} and of the second is {}.'.format(np.average(i), np.average(j)))

The average of the first sample is 0.5542998737686013 and of the second is 0.45336534640073695


**Арифметическое среднее**

In [29]:
print('Means are {} and {} respectively.'.format(np.mean(i), np.mean(j)))

Means are 0.5542998737686013 and 0.45336534640073695 respectively


 **Time weighted average (TWA)** - чем ближе к концу, тем больше влияет на результат

In [31]:
t = np.arange(len(i)) # создаем ряд 

In [33]:
np.average(i, weights=t) # реализуем, используя в качестве весов значение t - чем ближе к концу, тем больше вес

0.5607535200556559

In [34]:
np.max(i) # находим максимальное значение

0.9795346515531873

In [35]:
np.min(j) # находим минимальное значение

0.04046407109493644

In [36]:
np.ptp(i) # находит разброс

0.9698913371766348

In [37]:
np.median(j) # медиана

0.4383870839501971

Реализация алгоритма поиска медианы вручную средствами NumPy

In [39]:
sorted_j = np.msort(j) # сортируем список по возрастанию

In [43]:
n = len(j)
if n % 2 == 0:
    med = (sorted_j[int(n/2)] + sorted_j[int((n - 1)/2)]) / 2
else:
    med = sorted_j[int((n-1)/2)]
print(med)

0.4383870839501971


In [44]:
np.var(i) # дисперсия

0.08581009529637855

In [50]:
np.mean((i - i.mean()) ** 2) # то же самое вручную; важно, используем не функцию, а метод .mean() для массивов

0.08581009529637855